### ISSUE TITLE
Integration Home-Assistant with light / switch for LED of APs

### ISSUE THREAD

**Issue by thundergreen** [ameyuuno/docker-unifi-led-light-switch#1]
Hello I came accross your nice project and was wonderig if it might bepossible to make a custom component for Home-Assistant with light switch? Wanna use this to turn on /ff and change color in my automations :)

**Comment by ameyuuno** [comment]
Hi @thundergreen !

I'm glad to see you found my project interesting!  (^_^) 
Unfortunately I do not use Home Assistant and its "ecosystem" so I do not know how to integrate this in Home Assistant.

Maybe next week I will read about Home Assistant plugin development and try to create it. If this is solved by the presence of several configuration files, then I will add it to this project. Otherwise, it would be more logical to create a separate project for the plugin. Or... maybe not ¯\\_(ツ)_/¯  ))

AFAIK changing color of UDM's LED is impossible via API T_T only turning on/off

**Comment by thundergreen** [comment]
fair enough! i actually use this https://github.com/nickovs/unificontrol which works really good. and it's implemented into home assistant. so if you still want to develope something maybe u can have a look at this repo or just leave it behind :) But anyway thanks for your response

**Comment by ameyuuno** [comment]
Thanks for this link! 
Maybe I will use it to do more automations with my UDM, but for this project - I think python library is overkill))) curl is enough to switch LED >~< But anyway - library is nice, I need to read more about it.
